{"name": "test_valid_login", "status": "broken", "statusDetails": {"message": "NameError: name 'json' is not defined", "trace": "@pytest.fixture(scope=\"session\")\n    def config():\n        try:\n            with open('data/config.json', 'r', encoding='utf-8') as f:\n>               config_data = json.load(f)\nE               NameError: name 'json' is not defined\n\nconftest.py:99: NameError"}, "description": "Test login with valid credentials", "attachments": [{"name": "test_valid_login_setup_error", "source": "3b6ccb9d-4db3-4073-be09-e50a0dd11fc3-attachment.txt", "type": "text/plain"}], "start": 1747139666407, "stop": 1747139666407, "uuid": "cdac73a6-774a-4b55-ab2d-89f3254d6dc4", "historyId": "ab68c09e23714aa68c720c2ca07c0ecf", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-LKP4IQM"}, {"name": "thread", "value": "16604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}